tasks/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='category_list'),
    path('show_category/<str:pk>/', views.show_category, name='show_category'),
    path('update/<str:page>/<str:pk>/', views.updateTask, name="update"),
    path('delete_task/<str:page>/<str:pk>/', views.deleteTask, name="delete_task"),
    path('create_task/<str:page>/', views.createTask, name="create_task"),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls'))
]

tasks/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    category = models.CharField(max_length=128, default='All')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

tasks/forms.py
from django import forms
from django.forms import ModelForm

from .models import *

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('title','complete',)

tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *

# Create your views here.
def index(request):

    numbers = []
    total = 0

    tasks = Task.objects.all()
    category_list = [
        'All',
        'Travel',
        'Music',
        'Work',
        'Home',
        'Study',
        'Art',
        'Shopping',
        'Others'
    ]
    
    for x in category_list:
        category_task_count = Task.objects.filter(category = x).count()
        numbers.append(category_task_count)

    for num in numbers:
        total = total + num

    data = zip(category_list, numbers)
        
    context = {
        'tasks': tasks,
        'data': data,
        'total': total
    }

    return render(request, 'tasks/index.html', context)


def show_category(request, pk):

    created_list = []

    if pk == 'All':
        tasks = Task.objects.all()
        for task in tasks:
            created = task.created
            created_list.append(created)
    else:
        tasks = Task.objects.filter(category=pk)
        for task in tasks:
            created = task.created
            created_list.append(created)

    tasks_number = tasks.count()

    img = pk.lower()
    category_name = pk.capitalize()
    data = zip(tasks, created_list)



    context = {
        'data':data,
        'img': img,
        'category_name': category_name,
        'tasks_number': tasks_number
    }

    return render(request, 'tasks/show_category.html', context)


def updateTask(request, pk, page):
    task = Task.objects.get(id=pk)

    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('/show_category/' + page + '/')

    context = { 
        'form':form, 
        'page': page
        }

    return render(request, 'tasks/update.html', context)


def deleteTask(request, pk, page):
	task = Task.objects.get(id=pk)

	if request.method == 'POST':
		task.delete()
		return redirect('/show_category/' + page + '/')

	context = {
            'task': task,
            'page': page
        }

	return render(request, 'tasks/delete_task.html', context)


def createTask(request, page):

    if request.method =='POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.category = page
            instance.save()
            return redirect('/show_category/' + page + '/')

    form = TaskForm()

    context = {
        'form': form,
        'page': page    
    }

    return render(request, 'tasks/create_task.html', context)

tasks/templates/tasks/action.html
{% extends "tasks/base.html" %}

{% load static %}

{% block action %}
    <div class="action-container">

        <!-- Top -->
        <div class="top-bar">
            {% block create_text %}
            {% endblock %}

            {% block update_text %}
            {% endblock %}

            {% block delete_text %}
            {% endblock %}
            
            <div class="right">
                <div id="toggle">
                    <label class="switch" for="checkbox">
                        <input type="checkbox" id="checkbox" />
                        <div class="slider round"></div>
                    </label>
                </div>
                
                {% block prev_create_link %}
                {% endblock %}

                {% block prev_update_link %}
                {% endblock %}

                {% block prev_delete_link %}
                {% endblock %}


            </div>
        </div>
        <!-- Top -->


        <!-- Image -->
        <div class="image-container">
            {% block create_task_image %}
            {% endblock %}
            
            {% block update_task_image %}
            {% endblock %}

            {% block delete_task_image %}
            {% endblock %}

        </div>
        <!-- Image -->
        

        <!-- Content -->
        <div class="content">
            {% block create_task %}
            {% endblock %}

            {% block delete_task %}
            {% endblock %}

            {% block update_task %}
            {% endblock %}
        </div>
        <!-- Content -->


    </div>
{% endblock %}

tasks/templates/tasks/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'tasks/fontawesome/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'tasks/fontawesome/css/regular.css' %}">
    <link rel="stylesheet" href="{% static 'tasks/fontawesome/css/solid.css' %}">
    <link rel="stylesheet" href="{% static 'tasks/fontawesome/css/brands.css' %}">
    <link rel="stylesheet" href="{% static 'tasks/fontawesome/css/light.css' %}">

    <link rel="stylesheet" href="{% static 'tasks/css/style.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Baloo+Tammudu+2:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    
    <title>ToDo App</title>
    
</head>
<body> 
    {% block firstscreen %}
    {% endblock %}

    {% block secondscreen %}
    {% endblock %}

    {% block action %}
    {% endblock %}
    <script src="{% static 'tasks/script/main.js' %}"></script>
</body>
</html>

tasks/templates/tasks/create_task.html
{% extends "tasks/action.html" %}

{% load static %}

{% block create_task %}
    <h3><span style="color: var(--top-cont-color);">Add</span> new task in {{ task }} category</h3>
    <form method="POST">
        {% csrf_token %}
        <label for="id_title">Task name</label>
        {{ form.title }}
        <p class="muted">Press Add to add the task in the current list, or Cancel to navigate to the previous page.</p>
        <div class="buttons">
            <input type="submit" name="Add">
            <a href="{% url 'show_category' page %}">Cancel</a>
        </div>
    </form>
{% endblock %}


{% block create_task_image %}
    <img src="{% static 'tasks/icons/add_task.svg' %}">
{% endblock %}

{% block prev_create_link %}
	<a href="{% url 'show_category' page %}"><i class="fal fa-times"></i></a>
{% endblock %}

{% block create_text %}
	<p>Add</p>
{% endblock %}

tasks/templates/tasks/delete_task.html
{% extends "tasks/action.html" %}

{% load static %}

{% block delete_task %}
	<h3>You are about to <span style="color: rgb(194, 33, 33);">delete</span> the following item:</h3>
	<p>Task named '{{ task }}' from category '{{ task.category }}'.</p>
	<form method="POST" action="">
		{% csrf_token %}
		<p class="muted">Press Yes to continue, or Cancel to navigate to the previous page.</p>
		<div class="buttons">
			<input type="submit" name="Proceed">
			<a href="{% url 'show_category' page %}">Cancel</a>
		</div>
	</form>
{% endblock %}


{% block delete_task_image %}
	<img src="{% static 'tasks/icons/delete.svg' %}">
{% endblock %}

{% block prev_delete_link %}
	<a href="{% url 'show_category' page %}"><i class="fal fa-times"></i></a>
{% endblock %}

{% block delete_text %}
	<p>Confirm</p>
{% endblock %}

tasks/templates/tasks/index.html
 {% extends "tasks/base.html" %}
 
 {% load static %}

    {% block firstscreen %}
        <!-- FIRST SCREEN -->
        <div id="first" class="container">
                
            <!-- Header -->
            <div class="header-inner">
                <h1>Lists</h1>

                <div id="toggle">
                    <img src="{% static 'tasks/icons/sun.png' %}" style="width: 20px;">
                    <label class="switch" for="checkbox">
                        <input type="checkbox" id="checkbox" />
                        <div class="slider round"></div>
                    </label>
                </div>
            </div>

            <!-- List items wrapper -->
            <div class="inner-content">
            
                <!-- Row -->
                <div class="row">

                    {% for category, numbers in data %}
                        <a href="{% url 'show_category' category %}" class="list">
                            <div class="icon">

                                {% with 'tasks/icons/'|add:category|add:'.png' as image_static %}
                                    <img class="category-icon" src="{% static image_static %}" >
                                {% endwith %}

                            </div>
                            <div class="main-description">
                                <h3>{{category}}</h3>

                                {% if category == 'All' %}
                                    <p>{{ total }} tasks</p>
                                {% else %}
                                    <p>{{numbers}} tasks</p>
                                {% endif %}

                            </div>
                        </a> 
                    {% endfor %}

                </div>
                <!-- Row -->

            </div>
            <!-- List item wrapper -->

            
            <!-- Bottom line -->
            <div class="bottom-line"></div>
            <!-- Bottom line -->


        </div>
        <!-- FIRST SCREEN -->
    {% endblock %}

tasks/templates/tasks/secondscreen.html
{% extends "tasks/index.html" %}

{% block secondscreen %}
    <!-- SECOND SCREEN -->
    <div id="second" class="container" style="display: none;">
        <div class="top">
            <div class="navbar">
                <i class="fal fa-chevron-left"></i>
                <i class="far fa-ellipsis-v"></i>
            </div>
            <div class="text">
                <div class="icon-circle">
                    <div class="icon">
                        <img class="replaceIcon" src="{% static 'tasks/icons/all.png ' %}" alt="">
                    </div>
                </div>
                <div class="replace-description">
                    <div id="toggle">Go Dark</div>
                    <h3>All</h3>
                    <p>32 Tasks</p>
                </div>
            </div>
        </div>
        <div class="bottom">
            
            <div class="bottom-line"></div>
            <a href="#" class="add">
                <i class="fal fa-plus"></i>
            </a>

            <div class="scroll-container">
                <!-- Note -->
                {% for task in tasks %}
                    <div class="note">
                        <div class="text">
                            <h4>{{ task}}</h4>
                            <p>16:00</p>
                        </div>
                        <input type="checkbox">
                    </div>
                {% endfor %} 
                <!-- Note -->
            </div>

        </div>
    </div>
    <!-- SECOND SCREEN -->
{% endblock %}

tasks/templates/tasks/show_category.html
{% extends "tasks/base.html" %}

{% load static %}

    {% block secondscreen %}
        <!-- SECOND SCREEN -->
        <div id="second" class="container">
            <div class="top">
                <div class="navbar">
                    <a href="{% url 'category_list' %}"><i class="fal fa-chevron-left"></i></a>

                    <div class="right">
                        <div id="toggle">
                            <img src="{% static 'tasks/icons/sun.png' %}" style="width: 20px;">
                            <label class="switch" for="checkbox">
                                <input type="checkbox" id="checkbox" />
                                <div class="slider round"></div>
                            </label>
                        </div>
                        <i class="far fa-ellipsis-v"></i>
                    </div>
                </div>
                <div class="text">
                    <div class="icon-circle">
                        <div class="icon">
                            {% with 'tasks/icons/'|add:img|add:'.png' as image_static %}
                                <img class="replaceIcon" src="{% static image_static %}">
                            {% endwith %}
                        </div>
                    </div>
                    <div class="replace-description">
                        <h3>{{ category_name }}</h3>
                        <p>{{ tasks_number }} Tasks</p>
                    </div>
                </div>
            </div>
            <div class="bottom">
                
                <div class="bottom-line"></div>

                <a href="{% url 'create_task' category_name %}" class="add">
                    <i class="fal fa-plus"></i>
                </a>

                <div class="scroll-container">
                    <!-- Note -->
                    {% for task, created in data %}
                        <div class="note">
                            <div class="text" style="display: flex; align-items: center;">
                                
                                {% if task.complete == True %}
                                    <img src="{% static 'tasks/icons/completed.png' %}" alt="Completed task">
                                {% else %}
                                    <img src="{% static 'tasks/icons/inprogress.png' %}" alt="In progress task">
                                {% endif %} 

                                <div class="description">
                                    {% if task.complete == True %}
                                        <del>{{ task }}</del>
                                    {% else %}
                                        <h4>{{ task }}</h4>
                                    {% endif %} 
                                    <p>{{created|date:"M - d - Y,  h:m"}}</p>
                                </div>
                            </div>
                            <div class="actions">
                                <a class="delete" href="{% url 'delete_task' category_name task.id %}"><i class="fal fa-trash-alt"></i></a>
                                <a class="update" href="{% url 'update' category_name task.id %}"><i class="fal fa-marker"></i></a>
                            </div>
                        </div>
                    {% endfor %} 
                    <!-- Note -->
                </div>

            </div>

        </div>
        <!-- SECOND SCREEN -->
    {% endblock %}

    

tasks/templates/tasks/update.html
{% extends "tasks/action.html" %}

{% load static %}

{% block update_task %}
    <h3>Modify task</h3>
    <form method="POST">
        {% csrf_token %}
        {{ form.title }}
        <div class="flex-input">
            <label for="id_complete">Task completed?  </label>
            {{ form.complete }}
        </div>
        <p class="muted">Press Modify to update the task details, or Cancel to navigate to the previous page.</p>
        <div class="buttons">
            <input type="submit" name="Modify">
            <a href="{% url 'show_category' page %}">Cancel</a>
        </div>
    </form>
{% endblock %}


{% block update_task_image %}
    <img src="{% static 'tasks/icons/update_task.svg' %}">
{% endblock %}

{% block prev_update_link %}
	<a href="{% url 'show_category' page %}"><i class="fal fa-times" style="color: var(--text-color);"></i></a>
{% endblock %}

{% block update_text %}
	<p>Update</p>
{% endblock %}